---

- name: Check if application is deployed
  stat:
    path: "{{ project_path }}/index.php"
  register: app_deployed

- name: Clone git repository if necessary
  include: clone.yml
  when: app_deployed.stat.exists == False

- name: Backup current app deployment
  include: backup.yml
  when: app_deployed.stat.exists

- name: Build {{ project_name }} application
  include: build.yml
