---
- hosts: web
  become: true
  become_method: sudo
  remote_user: "vagrant"

  roles:
    - base
    - web

- hosts: db
  become: true
  become_method: sudo
  remote_user: "vagrant"

  roles:
    - base
    - db
