scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    target_groups:
      - targets: ['localhost:9100']
