---

- name: Set MySQL debconf root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: "{{ mysql_root_pw }}"
    vtype: password
  changed_when: false

- name: Confirm MySQL root password
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: "{{ mysql_root_pw }}"
    vtype: password
  changed_when: false

- name: Enable MySQL port in UFW
  ufw:
    rule: allow
    port: "{{mysql_port}}"
    from_ip: "{{ hostvars[item]['ansible_host'] }}"
  with_items:
    - "{{ groups['web'] }}"

- name: Install MySQL
  apt:
    package: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - mysql-server
    - mysql-client

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Remove anonymous MySQL user
  mysql_user:
    user: ""
    state: absent
    login_user: root
    login_password: "{{ mysql_root_pw }}"

- name: Apply configuration template
  template:
    src: remote.cnf.j2
    dest: /etc/mysql/conf.d/remote.cnf
    mode: 0644
  notify:
    - restart mysql
