---

- name: Lockdown DB with UFW
  ufw:
    state: enabled
    policy: deny
    logging: "on"

- name: UFW - Enable ports
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
  with_items: "{{ ufw_ports }}"

- name: Enable MySQL port
  ufw:
    rule: allow
    port: "{{mysql_port}}"
    from_ip: "{{ hostvars[item]['ansible_host'] }}"
  with_items:
    - "{{ groups['web'] }}"
