---

- name: Lockdown DB with UFW
  ufw:
    state: enabled
    policy: deny
    logging: "on"

- name: Enable MySQL port
  ufw:
    rule: allow
    port: "{{mysql_port}}"
    from_ip: "{{ hostvars[item]['ansible_host'] }}"
  with_items:
    - "{{ groups['web'] }}"
