---

- name: Prepare database for Vanilla
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "root"
    login_password: "{{ mysql_root_pw }}"

- name: Grant access to {{ project_user }}
  mysql_user:
    name: "{{ project_user }}"
    password: "{{ db_password }}"
    state: present
    priv: "{{ db_name }}.*:ALL"
    host: "{{ hostvars[groups['web'][0]]['ansible_host'] }}"
    login_user: "root"
    login_password: "{{ mysql_root_pw }}"
