---

- name: Install Apache
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - apache2-utils

- name: Enable Apache mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - restart apache2

- name: Create virtual host file
  template:
    src: vanilla_forum.conf.j2
    dest: /etc/apache2/sites-available/{{ project_name }}.conf
