---

- name: Install Apache
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - apache2-utils

- name: Enable Apache mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - restart apache2

- name: Create virtual host file
  template:
    src: vanilla_forum.conf.j2
    dest: /etc/apache2/sites-available/{{ project_name }}.conf

- name: Enable {{ project_name }}
  command: a2ensite {{ project_name }}
  args:
    creates: /etc/apache2/sites-enabled/{{ project_name }}.conf
  notify:
    - restart apache2

- name: Disable default apache site
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - restart apache2

- name: Clean Apache test page
  file:
    path: "{{ web_root }}/html/"
    state: absent
  notify:
    - restart apache2
