---

# Mega-module before being broken down into subs

# UFW
- name: Lockdown with UFW
  ufw: state=enabled policy=deny logging=on

- name: UFW - Enable incoming items
  ufw: rule=allow name={{ item }}
  with_items:
    - ssh
    - http
    - https

# Apache


# MySQL client


# PHP


# phpMyAdmin


# Git


# Composer


# Vanilla Forum
