---

# Mega-module before being broken down into subs

# UFW
- include: ufw.yml

# Apache
- include: apache.yml

# MySQL client
- include: mysql.yml

# PHP
- include: php.yml

# phpMyAdmin


# Git


# Composer


# Vanilla Forum
