---

- name: Install PHP packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - php5-curl
    - php-pear

- name: Enable PHP5 mcrypt
  shell: php5enmod mcrypt
  args:
    creates: /etc/php5/cli/conf.d/20-mcrypt.ini

- name: Install phing via pear
  shell: pear channel-discover pear.phing.info && pear install phing/phing
  args:
    creates: /usr/bin/phing

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  changed_when: false
