---

- name: Clean Apache test page
  file:
    path: "{{ git_path }}/html/"
    state: absent

- name: Clone git repository
  git:
    repo: "{{ git_repo }}"
    dest: "{{ git_path }}"
    force: yes

- name: Build Vanilla with Phing
  shell: phing
  args:
    chdir: "{{ git_path }}/build/"
    creates: vanilla-*.zip

- name: Check that Vanilla Forum directory exists
  file:
    path: "{{ project_path }}"
    state: directory    

- name: Unpack built archive of Vanilla Forum
  unarchive:
    src: "{{ git_path }}/build/vanilla-*.zip"
    dest: "{{ project_path }}"
    copy: no
